# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KE <- function(X, k_vec = NULL, toll = 1e-4, min_size_ts = NULL, max_size_ts = NULL, num_threads = NULL, id_rem_nan = NULL) {
    .Call('_KePredictor_KE', PACKAGE = 'KePredictor', X, k_vec, toll, min_size_ts, max_size_ts, num_threads, id_rem_nan)
}

KEI <- function(X, k_vec = NULL, toll = 1e-4, min_size_ts = NULL, max_size_ts = NULL, num_threads = NULL, id_rem_nan = NULL) {
    .Call('_KePredictor_KEI', PACKAGE = 'KePredictor', X, k_vec, toll, min_size_ts, max_size_ts, num_threads, id_rem_nan)
}

