# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KE_1d <- function(X, id_algo = "KE", k_vec = NULL, toll = 1e-4, min_size_ts = NULL, max_size_ts = NULL, num_threads = NULL, id_rem_nan = NULL) {
    .Call('_KePredictor_KE_1d', PACKAGE = 'KePredictor', X, id_algo, k_vec, toll, min_size_ts, max_size_ts, num_threads, id_rem_nan)
}

KEI_1d <- function(X, id_algo = "KE", k_vec = NULL, toll = 1e-4, min_size_ts = NULL, max_size_ts = NULL, num_threads = NULL, id_rem_nan = NULL) {
    .Call('_KePredictor_KEI_1d', PACKAGE = 'KePredictor', X, id_algo, k_vec, toll, min_size_ts, max_size_ts, num_threads, id_rem_nan)
}

KE_2d <- function(X, id_algo = "KE", k = 0L, threshold_ppc = 0.95, k_vec = NULL, toll = 1e-4, num_disc_ev_x1 = 10L, num_disc_ev_x2 = 10L, min_size_ts = NULL, max_size_ts = NULL, num_threads = NULL, id_rem_nan = NULL) {
    .Call('_KePredictor_KE_2d', PACKAGE = 'KePredictor', X, id_algo, k, threshold_ppc, k_vec, toll, num_disc_ev_x1, num_disc_ev_x2, min_size_ts, max_size_ts, num_threads, id_rem_nan)
}

KEI_2d <- function(X, id_algo = "KE", k = 0L, threshold_ppc = 0.95, k_vec = NULL, toll = 1e-4, num_disc_ev_x1 = 10L, num_disc_ev_x2 = 10L, min_size_ts = NULL, max_size_ts = NULL, num_threads = NULL, id_rem_nan = NULL) {
    .Call('_KePredictor_KEI_2d', PACKAGE = 'KePredictor', X, id_algo, k, threshold_ppc, k_vec, toll, num_disc_ev_x1, num_disc_ev_x2, min_size_ts, max_size_ts, num_threads, id_rem_nan)
}

data_2d_wrapper_from_list_ke <- function(Xt) {
    .Call('_KePredictor_data_2d_wrapper_from_list_ke', PACKAGE = 'KePredictor', Xt)
}

